import { useNavigate, useParams } from "react-router-dom";
import ScoreGauge from "@/components/ScoreGauge";
import MetricBar from "@/components/MetricBar";
import { mockScores, mockRecommendation } from "@/data/mockData";

const SharePage = () => {
  const navigate = useNavigate();
  const { id } = useParams();

  return (
    <div className="min-h-screen bg-background-dark font-display">
      <div className="flex items-center justify-between px-6 py-4 border-b border-white/5 dv-topbar">
        <div className="flex items-center gap-2">
          <span className="material-symbols-outlined text-primary">flare</span>
          <span className="font-black text-ivory">Dental Vision</span>
        </div>
        <button
          onClick={() => navigate("/")}
          className="px-4 py-2 bg-primary text-white rounded-full text-xs font-bold hover:opacity-90 transition-opacity"
        >
          Analyse Your Smile →
        </button>
      </div>

      <div className="max-w-2xl mx-auto px-6 py-10">
        <div className="bg-primary/10 border border-primary/20 rounded-2xl p-4 flex items-center gap-3 mb-8">
          <span className="material-symbols-outlined text-primary">share</span>
          <span className="text-sm dv-muted">You're viewing a shared Dental Vision scan report for scan {id}.</span>
          <button onClick={() => navigate("/")} className="text-primary font-bold underline text-sm ml-auto shrink-0">
            Try it free →
          </button>
        </div>

        <div className="bg-card-dark rounded-3xl p-8 flex flex-col items-center gap-6 border border-white/10 shadow-2xl">
          <ScoreGauge score={mockScores.overall} size={148} strokeWidth={12} />
          <span className="text-[10px] font-black uppercase tracking-widest text-ivory">SMILE HEALTH SCORE</span>

          <div className="w-full grid grid-cols-2 gap-3">
            <MetricBar label="Alignment" value={mockScores.alignment} icon="straighten" />
            <MetricBar label="Symmetry" value={mockScores.symmetry} icon="compare_arrows" />
            <MetricBar label="Whiteness" value={mockScores.whiteness} icon="brightness_high" />
            <MetricBar label="Spacing" value={mockScores.spacing} icon="space_bar" />
          </div>

          <span className="text-xs dv-muted">Scanned on May 12, 2025</span>
          <p className="text-[10px] dv-muted text-center">
            This score was generated by Dental Vision AI and is for informational purposes only.
          </p>
        </div>

        <div className="mt-8 rounded-2xl overflow-hidden border border-white/10 bg-card-dark">
          <div className="grid grid-cols-1 md:grid-cols-2">
            <div className="relative aspect-[4/3] overflow-hidden bg-background-dark">
              <img
                src="https://images.unsplash.com/photo-1606811841689-23dfddce3e95?w=800"
                alt="Original"
                className="h-full w-full object-cover"
              />
              <span className="absolute bottom-4 left-4 bg-black text-white px-3 py-1 text-[10px] font-bold uppercase">Original</span>
            </div>
            <div className="flex aspect-[4/3] flex-col items-center justify-center gap-4 bg-gradient-to-br from-primary/10 via-white/0 to-primary/15 p-8 text-center">
              <div className="size-16 rounded-2xl border border-primary/20 bg-primary/10 flex items-center justify-center text-primary">
                <span className="material-symbols-outlined text-3xl">animation</span>
              </div>
              <div>
                <p className="text-sm font-black uppercase tracking-[0.24em] text-primary">Simulation pending</p>
                <p className="mt-2 text-sm dv-muted leading-relaxed">
                  No fallback simulation image is shown here. Shared ML previews will appear after model rollout.
                </p>
              </div>
            </div>
          </div>
        </div>

        <div className="bg-primary/10 border border-primary/20 rounded-2xl p-6 mt-8">
          <div className="flex items-center gap-3 mb-3">
            <span className="material-symbols-outlined text-primary">lightbulb</span>
            <span className="text-sm font-black uppercase text-ivory">AI RECOMMENDATION</span>
          </div>
          <p className="text-sm text-ivory leading-relaxed">{mockRecommendation.summary}</p>
        </div>

        <div className="flex flex-col items-center gap-4 mt-10 text-center">
          <h3 className="text-xl font-black text-ivory">Want to know your smile score?</h3>
          <p className="text-sm dv-muted">Get your free AI dental analysis in under 60 seconds.</p>
          <button
            onClick={() => navigate("/")}
            className="px-8 py-3 bg-primary text-white rounded-full font-black text-sm hover:opacity-90 transition-opacity"
          >
            Analyse My Smile — It's Free
          </button>
        </div>
      </div>
    </div>
  );
};

export default SharePage;
